spring.application.name: mycms
server.port: 8888

#logging
logging:
  level: info
  config: classpath:logback.xml

#mybatis配置
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mappers/*.xml
  type-aliases-package: org.jon.lv.domain

#数据库设置
datasource:
  type: com.alibaba.druid.pool.DruidDataSource
#spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mycms?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

